### ISSUE TITLE
Dont work make on Ubuntu 16

### ISSUE THREAD

**Issue by dtilyupo** [EnterpriseDB/mongo_fdw#98]
Hi.
I try to install mongo_fdw. I have next errors after steps:
git clone https://github.com/EnterpriseDB/mongo_fdw.git --recursive
cd mongo_fdw/
sudo ./autogen.sh --with-legacy
sudo make
[...]
src/env.c: In function ‘mongo_env_socket_connect’:
src/env.c:318:21: error: storage size of ‘ai_hints’ isn’t known
     struct addrinfo ai_hints;
                     ^
src/env.c:339:14: warning: implicit declaration of function ‘getaddrinfo’ [-Wimplicit-function-declaration]
     status = getaddrinfo( host, port_str, &ai_hints, &ai_list );
              ^
src/env.c:341:51: warning: implicit declaration of function ‘gai_strerror’ [-Wimplicit-function-declaration]
         bson_errprintf( "getaddrinfo failed: %s", gai_strerror( status ) );
                                                   ^
src/env.c:346:60: error: dereferencing pointer to incomplete type ‘struct addrinfo’
     for ( ai_ptr = ai_list; ai_ptr != NULL; ai_ptr = ai_ptr->ai_next ) {
                                                            ^
src/env.c:379:5: warning: implicit declaration of function ‘freeaddrinfo’ [-Wimplicit-function-declaration]
     freeaddrinfo( ai_list );
     ^
src/env.c:318:21: warning: unused variable ‘ai_hints’ [-Wunused-variable]
     struct addrinfo ai_hints;
                     ^
Makefile:216: recipe for target 'src/env.os' failed
make[1]: *** [src/env.os] Error 1
make[1]: Leaving directory '/home/tilyupo/test/mongo_fdw/mongo-c-driver'
Makefile:33: recipe for target 'mongo-c-driver/src/env.os' failed
make: *** [mongo-c-driver/src/env.os] Error 2
Can someone help me?

**Comment by nonchalant-enthusiast** [comment]
report the same issue

**Comment by martinhv** [comment]
same here with ubuntu 16.04.4

**Comment by omkz** [comment]
@stephaneDunand Thank you. It also works on ubuntu 20.04

**Comment by vaibhavdalvi93** [comment]
Hi @omkz, @martinhv and @dtilyupo,

Can you please confirm that reported issue is been resolved or not on latest HEAD? If it's been resolved then could you please close this ticket?
